INSERT INTO Authors VALUES ("George Orwell", "A01");
INSERT INTO Authors VALUES ("Gabriel Garcia Marquez", "A02");
INSERT INTO Authors VALUES ("Aldous Huxley", "A03");
INSERT INTO Authors VALUES ("Fyodor Dostoevsky", "A04");
INSERT INTO Authors VALUES ("C.S. Lewis", "A05");
INSERT INTO Authors VALUES ("Mary Shelley", "A06");
INSERT INTO Authors VALUES ("John Steinbeck", "A07");
INSERT INTO Authors VALUES ("Mark Twain", "A08");
INSERT INTO Authors VALUES ("Charles Dickens", "A09");
INSERT INTO Authors VALUES ("Joseph Heller", "A10");
INSERT INTO Authors VALUES ("Homer", "A11");
INSERT INTO Authors VALUES ("Victor Hugo", "A12");
INSERT INTO Authors VALUES ("James Joyce", "A13");
INSERT INTO Authors VALUES ("Vladimir Nabokov", "A14");
INSERT INTO Authors VALUES ("Ayn Rand", "A15");
INSERT INTO Authors VALUES ("Patrick Suskind", "A16");
INSERT INTO Authors VALUES ("Franz Kafka", "A17");
INSERT INTO Authors VALUES ("Bret Easton Ellis", "A18");
INSERT INTO Authors VALUES ("Rene Goscinny", "A19");
INSERT INTO Authors VALUES ("Albert Uderzo", "A19");
INSERT INTO Authors VALUES ("Ray Bradbury", "A20");
INSERT INTO Authors VALUES ("Isaac Asimov", "A21");
INSERT INTO Authors VALUES ("Karl Marx", "A22");
INSERT INTO Authors VALUES ("Friedrich Engels", "A22");
INSERT INTO Authors VALUES ("Thomas Paine", "A23");
INSERT INTO Authors VALUES ("Niccolo Machiavelli", "A24");
INSERT INTO Authors VALUES ("Adam Smith", "A25");
INSERT INTO Authors VALUES ("Miguel de Cervantes Saavedra", "A26");
INSERT INTO Authors VALUES ("Simone de Beauvoir", "A27");
INSERT INTO Authors VALUES ("Immanuel Kant", "A28");
INSERT INTO Authors VALUES ("Charles Darwin", "A29");
INSERT INTO Authors VALUES ("Isaac Newton", "A30");
INSERT INTO Authors VALUES ("Milan Kundera", "A31");
INSERT INTO Authors VALUES ("Sun Tzu", "A32");
INSERT INTO Authors VALUES ("Jorge Luis Borges", "A33");
INSERT INTO Authors VALUES ("Gabriel Garcia Marquez", "A34");
INSERT INTO Authors VALUES ("Juan Rulfo", "A35");
INSERT INTO Authors VALUES ("Octavio Paz", "A36");
INSERT INTO Authors VALUES ("Pablo Neruda", "A37");
INSERT INTO Authors VALUES ("Richard Feynman", "A38");
INSERT INTO Authors VALUES ("Stephen Hawking", "A39");
INSERT INTO Authors VALUES ("Carl Sagan", "A40");
INSERT INTO Authors VALUES ("Silvanus P. Thompson", "A41");
INSERT INTO Authors VALUES ("Martin Gardner", "A41");
INSERT INTO Authors VALUES ("Enrico Fermi", "A42");
INSERT INTO Authors VALUES ("Alexander Hamilton", "A43");
INSERT INTO Authors VALUES ("James Madison", "A43");
INSERT INTO Authors VALUES ("John Jay", "A43");
INSERT INTO Authors VALUES ("John Lcke", "A44");
INSERT INTO Authors VALUES ("C. B. Macpherson", "A44");
INSERT INTO Authors VALUES ("Karl Popper", "A45");
INSERT INTO Authors VALUES ("Howard Zinn", "A46");
INSERT INTO Authors VALUES ("William Golding", "A47");
INSERT INTO Authors VALUES ("George Orwell", "A48");
INSERT INTO Authors VALUES ("Ernest Hemingway", "A49");
INSERT INTO Authors VALUES ("Luo Guanzhong", "A50");